name: ml-book
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - numpy=1.21.2
  - pandas=1.3.2
  - scipy=1.7.0
  - python=3.9
  - matplotlib=3.4.3
  - scikit-learn=1.0
  - jupyterlab>=3.4.4
  - pip
  - pip:
    - torch==1.9.0
    - torchtext==0.10.0

